version: '3.7'
services:
  api:
    build:
      context: "./api"
    ports:
    - "8000:8000"
    networks:
      - app-network

  client:
    build:
      context: "./client"
    ports:
    - "8501:8501"
    depends_on:
      - api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge